# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'meh.com' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Crashlytics', '~> 3.10.5'
  pod 'CTFeedback'
  pod 'Fabric', '~> 1.7.9'
  pod 'Firebase/AdMob'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Nuke'
  pod 'QuickTableViewController'
  pod 'SwiftyMarkdown'
end

target 'Meh Deal' do
    use_frameworks!
    
end

target 'Meh Notification Service Extension' do
    use_frameworks!
    
end
